services:
  next-posts-frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: next-posts-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules


