services:
  next-posts-frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: next-posts-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
  db-posts:
    image: postgres:14
    container_name: db-posts
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-posts
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin-posts:
      image: dpage/pgadmin4
      container_name: pgadmin-posts
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - db-posts
      volumes:
        - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data:

